# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(max_length=1000)),
                ('image', models.FileField(default='', upload_to='')),
                ('director', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=200)),
                ('links', models.CharField(max_length=1000)),
                ('movie_date', models.DateTimeField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
