# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_new_uploaded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_recommended',
            field=models.BooleanField(default=True),
        ),
    ]
