# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170826_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='images/car1.jpg', upload_to=''),
        ),
    ]
