# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20170827_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='directores',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='link',
            name='name',
        ),
        migrations.AddField(
            model_name='actor',
            name='html_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='category',
            name='html_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='country',
            name='html_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='director',
            name='html_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='genre',
            name='html_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='link',
            name='website_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movies.MovieWebsite'),
        ),
        migrations.AddField(
            model_name='moviewebsite',
            name='html_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='moviewebsite',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
