# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20170828_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='images/car1.jpg', upload_to='movies'),
        ),
    ]
