# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='/carousel/default_image.jpg', upload_to='')),
                ('subtitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationBarButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
