# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraapps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationBarButton',
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.FileField(default='carousel/default_image.jpg', upload_to='carousel'),
        ),
    ]
